### ISSUE TITLE
YAML config should be capable of filtering clusters and jobs by specific criteria

### ISSUE THREAD

**Issue by neilbest-db** [databrickslabs/databricks-sync#79]
Rather than sync-ing everything, let's make it possible to list the required objects by name, ID, and/or association.

My immediate requirement is to migrate all jobs associated with a particular named, interactive cluster, for example.  These will also depend on other objects, i.e. users/groups and cluster policies, but that may be a taller order.  Let's get something like this working for now at a minimum:

```yaml
jobs:
  by:
    existing_cluster_ids:
      - "id...."
      - "id...."
cluster:
  by:
    name:
      - "...."
    id:
      - "id...."
      - "id...."
```

Taken from [this Slack thread](https://databricks.slack.com/archives/G019V9STDQ9/p1620753987024300) w/ @stikkireddy.
